# Build a Qt project on Windows
name: Build on Windows

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]
  workflow_dispatch:

jobs:
  build:

    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v4            
    - name: Setup MSVC Developer Command Prompt
      # You may pin to the exact commit or the version.
      # uses: TheMrMilchmann/setup-msvc-dev@fb19abb8a41b3cf0340f5d1be17d420309232be6
      uses: TheMrMilchmann/setup-msvc-dev@v3.0.1
    - name: Install Qt
      uses: jurplel/install-qt-action@v4
      with:
        version: '5.12.8'
        host: 'windows'
        target: 'desktop'
        arch: 'win64_msvc2017_64'
        # modules: 'gui core serialport network opengl xml'
    - name: qmake
      run: qmake .
    - name: make
      run: make
    - name: make check
      run: make check

#    - name: make distcheck
#      run: make distcheck
